name: Site Check

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  verify:
    name: Verify static assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure landing page exists
        run: test -s index.html

      - name: Ensure CSS bundle exists
        run: test -s assets/style.css
